server:
  port: 8511

spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.mysql.host}:${app.mysql.port}/${app.mysql.dbname}?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${app.mysql.username}
    password: ${app.mysql.password}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml


app:
  mysql:
    host: 192.168.73.128
    port: 3306
    dbname: db_pycslt
    username: root
    password: 12345678