server:
  port: 6815
# 配置数据库连接信息
spring:
  application:
    name: pycslt-manager
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.mysql.host}:${app.mysql.port}/${app.mysql.dbname}?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${app.mysql.username}
    password: ${app.mysql.password}
  # Redis的相关配置
  data:
    redis:
      host: ${app.redis.host}
      port: ${app.redis.port}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml
# mybatis-flex 配置
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  minio:
    endpoint-url: http://centos:9000
    access-key: admin
    secret-key: 12345678
    bucket-name: pycslt-bucket
  auth:
    no-auth-urls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
  mysql:
    host: 192.168.73.128
    port: 3306
    dbname: db_pycslt
    username: root
    password: 12345678
  redis:
    host: 192.168.73.128
    port: 6379
