server:
  port: 6820



spring:
  application:
    name: service-pay
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: ${app.nacos.host}:${app.nacos.port}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.mysql.host}:${app.mysql.port}/${app.mysql.dbname}?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${app.mysql.username}
    password: ${app.mysql.password}
  data:
    redis:
      host: ${app.redis.host}
      port: ${app.redis.port}
  config:
    import: optional:application-alipay.yml

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  mysql:
    host: 192.168.73.128
    port: 3306
    dbname: db_pycslt
    username: root
    password: 12345678
  redis:
    host: 192.168.73.128
    port: 6379
  nacos:
    host: 192.168.73.128
    port: 8848